#!/bin/bash

export PATH=$PATH:/usr/bin
yarn add immutable 
yarn add commander
yarn add express

yarn add --dev style-loader
yarn add --dev css-loader
yarn add --dev stylus-loader stylus
yarn add --dev @types/react @types/react-dom
yarn add webpack
